" Language syntaxes.
Plugin 'Nemo157/glsl.vim'
Plugin 'plasticboy/vim-markdown'
Plugin 'kchmck/vim-coffee-script'
Plugin 'PProvost/vim-ps1'
Plugin 'dimituri/JSON.vim'
Plugin 'Nemo157/llvm.vim'
Plugin 'Nemo157/scala.vim'
Plugin 'Nemo157/rpn.vim'
Plugin 'tanob/mirah-vim'
Plugin 'zaiste/tmux.vim'
