" Language syntaxes.
Plugin 'Nemo157/glsl.vim'
Plugin 'plasticboy/vim-markdown'
Plugin 'kchmck/vim-coffee-script'
Plugin 'PProvost/vim-ps1'
Plugin 'dimituri/JSON.vim'
Plugin 'Nemo157/llvm.vim'
Plugin 'Nemo157/scala.vim'
Plugin 'Nemo157/rpn.vim'
Plugin 'tanob/mirah-vim'
Plugin 'zaiste/tmux.vim'
Plugin 'elixir-lang/vim-elixir'
Plugin 'KohPoll/vim-less'
Plugin 'slim-template/vim-slim'
Plugin 'leafgarland/typescript-vim'
Plugin 'raichoo/purescript-vim'
Plugin 'mustache/vim-mustache-handlebars'
