#!/usr/bin/env zsh

set -eu

if [ "$1" = "rubber" ]
then
  shift
fi

manifest=()
case "${1:-}" in
  --manifest-path=*)
    manifest+="$1"
    shift
    ;;
  --manifest-path)
    manifest+="--manifest-path=$2"
    shift
    shift
    ;;
esac

subcommand="${1:?missing subcommand}"
shift

echo '    [36;1mFetching[0m dependencies' >&2
cargo fetch "$manifest[@]" --locked

root="$(cargo metadata "$manifest[@]" --format-version 1 | jq -r .workspace_root)"
target_dir="$(cargo metadata "$manifest[@]" --format-version 1 | jq -r .target_directory)"
mkdir -p "$target_dir"

echo '     [36;1mRunning[0m `cargo '"$subcommand$([ $# -gt 0 ] && echo " ")$@"'`' >&2
bwrap \
  --ro-bind / / \
  --tmpfs /tmp \
  --dev /dev \
  --tmpfs /run \
  --ro-bind "$root" "$root" \
  --bind "$target_dir" "$target_dir" \
  --unshare-net \
  cargo \
    "$subcommand" \
    "$manifest[@]" \
    "$@"
