{
 "title": "Main dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "Services/Apps - $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "host",
   "collapsed": true,
   "panels": [
    {
     "title": "System Service CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "alias": "$tag_path",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "path::tag" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cgroup",
       "select": [
        [
         { "params": [ "cpu.stat.usage_usec" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / ($__interval_ms * 1000)" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=~", "value": "/system\\.slice\\//" },
        { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "User Service CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "alias": "$tag_path",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "path::tag" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cgroup",
       "select": [
        [
         { "params": [ "cpu.stat.usage_usec" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / ($__interval_ms * 1000)" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=~", "value": "/user\\.slice\\//" },
        { "condition": "AND", "key": "path::tag", "operator": "=~", "value": "/\\.service$/" },
        { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "System Service Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "$tag_path",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "path::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cgroup",
       "select": [
        [
         { "params": [ "memory.current" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=~", "value": "/system\\.slice\\//" },
        { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "User Service Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "$tag_path",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "path::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cgroup",
       "select": [
        [
         { "params": [ "memory.current" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=~", "value": "/user\\.slice\\//" },
        { "condition": "AND", "key": "path::tag", "operator": "=~", "value": "/\\.service$/" },
        { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Apps CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "alias": "$tag_path",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "path::tag" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cgroup",
       "query": "SELECT non_negative_difference(mean(\"cpu.stat.usage_usec\"))  / ($__interval_ms * 1000) FROM \"cgroup\" WHERE (\"path\"::tag =~ /user-1000\\.slice/ AND \"path\"::tag =~ /app\\.slice\\/app-[^\\/]+\\.(slice|scope)$/ AND \"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\"::tag, \"path\"::tag fill(none)",
       "select": [
        [
         { "params": [ "cpu.stat.usage_usec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / ($__interval_ms * 1000)" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=~", "value": "/user-1000\\.slice/" },
        {
         "condition": "AND",
         "key": "path::tag",
         "operator": "=~",
         "value": "/app\\.slice\\/app-[^\\/]+\\.(slice|scope)$/"
        },
        { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Apps Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "$tag_path",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "path::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cgroup",
       "select": [
        [
         { "params": [ "memory.current" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "path::tag", "operator": "=~", "value": "/user-1000\\.slice/" },
        {
         "condition": "AND",
         "key": "path::tag",
         "operator": "=~",
         "value": "/app\\.slice\\/app-[^\\/]+\\.(slice|scope)$/"
        },
        { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Usage - $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "host" },
  {
   "title": "Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "cpu::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"host\"::tag =~ /^$host$/) AND (\"cpu\"::tag = 'cpu-total') AND $timeFilter GROUP BY time($__interval), \"host\"::tag fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "usage_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host - GPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "query": "SELECT mean(\"utilization_gpu\") FROM \"nvidia_smi\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\"::tag fill(null)",
     "select": [
      [
       { "params": [ "utilization_gpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_host - Decode",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "select": [
      [
       { "params": [ "utilization_decoder" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_host - Encode",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "select": [
      [
       { "params": [ "utilization_encoder" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_host - cgroup",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cgroup",
     "select": [
      [
       { "params": [ "cpu.stat.usage_usec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / ($__interval_ms * 1000)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "path::tag", "operator": "=", "value": "/sys/fs/cgroup" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_host - system",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cgroup",
     "select": [
      [
       { "params": [ "cpu.stat.usage_usec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / ($__interval_ms * 1000)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "path::tag", "operator": "=", "value": "/sys/fs/cgroup/system.slice" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_host - user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cgroup",
     "select": [
      [
       { "params": [ "cpu.stat.usage_usec" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ " / ($__interval_ms * 1000)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "path::tag", "operator": "=", "value": "/sys/fs/cgroup/user.slice" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_host - GPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "amd_rocm_smi",
     "query": "SELECT mean(\"utilization_gpu\") FROM \"nvidia_smi\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\"::tag fill(null)",
     "select": [
      [
       { "params": [ "utilization_gpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host - CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_host - GPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "query": "SELECT (mean(\"memory_used\") / mean(\"memory_total\")) * 100 FROM \"nvidia_smi\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\"::tag fill(null)",
     "select": [
      [
       { "params": [ "memory_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "memory_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host - GPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "query": "SELECT (mean(\"memory_used\") / mean(\"memory_total\")) * 100 FROM \"amd_rocm_smi\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\"::tag fill(null)",
     "select": [
      [
       { "params": [ "memory_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "memory_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Categories",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "total $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    { "expression": "$preused - $arc", "type": "math" },
    {
     "alias": "arc $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zfs",
     "select": [
      [
       { "params": [ "arcstats_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "cached $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "buffered $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "buffered" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "free $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "swap $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Temp - $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "host",
   "collapsed": true,
   "panels": [
    {
     "title": "Temperatures",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "alias": "$tag_host - $tag_chip - $tag_feature",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "feature::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sensors",
       "select": [
        [
         { "params": [ "temp_input" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "$tag_host - GPU",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nvidia_smi",
       "select": [
        [
         { "params": [ "temperature_gpu" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Fan speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_host - GPU",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "nvidia_smi",
       "select": [
        [
         { "params": [ "fan_speed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "$tag_host - $tag_chip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "chip::tag" ], "type": "tag" },
        { "params": [ "feature::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sensors",
       "query": "SELECT ((mean(\"fan_input\") - mean(\"fan_min\")) / (mean(\"fan_max\") - mean(\"fan_min\"))) * 100 FROM \"sensors\" WHERE (\"host\"::tag =~ /^$host$/) AND $timeFilter GROUP BY time($__interval), \"host\"::tag, \"chip\"::tag fill(null)",
       "select": [
        [
         { "params": [ "fan_input" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "fan_max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Frequency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "linux_cpu",
       "select": [
        [
         { "params": [ "scaling_cur_freq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "* 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network - $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "host",
   "collapsed": true,
   "panels": [
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "$tag_host - $tag_interface ↓",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "interface::tag" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "net",
       "query": "SELECT non_negative_difference(last(\"bytes_recv\")) / $__interval_ms * 1000 FROM \"net\" WHERE $timeFilter GROUP BY time($__interval), \"host\"::tag, \"interface\"::tag fill(null)",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / $__interval_ms * 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "interface::tag", "operator": "!~", "value": "/^(veth|br-)/" },
        { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "$tag_host - $tag_interface ↑",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "interface::tag" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / $__interval_ms * 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "interface::tag", "operator": "!~", "value": "/^(veth|br-)/" },
        { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host - TCP Established",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netstat",
       "select": [
        [
         { "params": [ "tcp_established" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "$tag_host - TCP Listen",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netstat",
       "select": [
        [
         { "params": [ "tcp_listen" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "$tag_host - UDP Sockets",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netstat",
       "select": [
        [
         { "params": [ "udp_socket" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Docker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Docker Containers CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_host - $tag_container_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "docker_container_cpu",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 24" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Docker Containers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker",
       "select": [
        [
         { "params": [ "n_containers" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "running",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker",
       "select": [
        [
         { "params": [ "n_containers_running" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "paused",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker",
       "select": [
        [
         { "params": [ "n_containers_paused" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "stopped",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker",
       "select": [
        [
         { "params": [ "n_containers_stopped" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Docker Containers Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "$tag_host - $tag_container_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_mem",
       "select": [
        [
         { "params": [ "usage" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Docker Containers Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "$tag_host - $tag_container_name ↓",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_net",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / $__interval_ms * 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "$tag_host - $tag_container_name ↑",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_net",
       "select": [
        [
         { "params": [ "tx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / $__interval_ms * 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Kind Containers CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_pod_name/$tag_container_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pod_name::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "kubernetes_pod_container",
       "select": [
        [
         { "params": [ "cpu_usage_nanocores" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 10000000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Kind Containers Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "$tag_pod_name/$tag_container_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pod_name::tag" ], "type": "tag" },
        { "params": [ "container_name::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kubernetes_pod_container",
       "select": [
        [
         { "params": [ "memory_working_set_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Kind Containers Network",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "$tag_pod_name ↓",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pod_name::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kubernetes_pod_network",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / $__interval_ms * 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "$tag_pod_name ↑",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pod_name::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kubernetes_pod_network",
       "select": [
        [
         { "params": [ "tx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / $__interval_ms * 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk - $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "host",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "$tag_host - $tag_path",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "path::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "fstype::tag", "operator": "!=", "value": "tmpfs" },
        { "condition": "AND", "key": "fstype::tag", "operator": "!=", "value": "efivarfs" },
        { "condition": "AND", "key": "fstype::tag", "operator": "!=", "value": "vfat" },
        { "condition": "AND", "key": "fstype::tag", "operator": "!=", "value": "devtmpfs" },
        { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "$tag_host - total",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "fstype::tag", "operator": "!=", "value": "tmpfs" },
        { "condition": "AND", "key": "fstype::tag", "operator": "!=", "value": "efivarfs" },
        { "condition": "AND", "key": "fstype::tag", "operator": "!=", "value": "vfat" },
        { "condition": "AND", "key": "fstype::tag", "operator": "!=", "value": "devtmpfs" },
        { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk IO",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "$tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "name::tag" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " / $__interval_ms * 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Free Space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "path::tag", "operator": "=", "value": "/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}